### ISSUE TITLE
could not read Username for 'https://github.com' whn using auto-commit action

### ISSUE THREAD

**Issue by karolis-arbaciauskas** [cds-snc/github-actions#23]
Hi. I'm facing error: `fatal: could not read Username for 'https://github.com': No such device or address`

Here is my config:

```yml
name: .NET Core CI

on: [push]

jobs:
  build:
    name: Generate epg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Filter release branch
      uses: actions/bin/filter@master
      with:
        args: branch release
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run with dotnet
      run: dotnet run
    - name: Auto-commit
      uses: docker://cdssnc/auto-commit-github-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_EPG_BOT_TOKEN }}
      with:
        args: This is an auto-commit
```
